### ISSUE TITLE
while building the app grtting following error

### ISSUE THREAD

**Issue by rajkishoreandia** [razorpay/react-native-razorpay#118]
Loading dependency graph, done.

{ Error
    at ResolutionRequest._resolveHasteDependency (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:125:15)
    at ModuleResolution.tryResolveSync (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:103:18)
    at Object.tryResolveSync (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:113:12)
    at ResolutionRequest.resolveDependency (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:102:39)
    at dependencyNames.map.name (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:136:10)
    at Array.map (<anonymous>)
    at ResolutionRequest.resolveModuleDependencies (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:135:42)
    at module.readFresh.then (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:183:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  fromModulePath: '/Users/uniquecreations/Desktop/latest-app/donate-us-pay/index.js',
  hasteError: 
   { Error: The name `react-native` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or blacklist files until there remains only one of these:

  * `/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/react-native-razorpay/node_modules/react-native/package.json` (package)
  * `/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/react-native/package.json` (package)

    at ModuleMap._assertNoDuplicates (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/jest-haste-map/build/module_map.js:129:11)
    at ModuleMap._getModuleMetadata (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/jest-haste-map/build/module_map.js:108:10)
    at ModuleMap.getModule (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/jest-haste-map/build/module_map.js:40:25)
    at ModuleResolver.resolveHasteDependency (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:148:48)
    at ResolutionRequest._resolveHasteDependency (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:122:17)
    at ModuleResolution.tryResolveSync (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:103:18)
    at Object.tryResolveSync (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:113:12)
    at ResolutionRequest.resolveDependency (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:102:39)
    at dependencyNames.map.name (/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:136:10)
    at Array.map (<anonymous>)
     hasteName: 'react-native',
     platform: 'g',
     supportsNativePlatform: true,
     duplicatesSet: 
      { '/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/react-native-razorpay/node_modules/react-native/package.json': 1,
        '/Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/react-native/package.json': 1 } } }

**Comment by iThink32** [comment]
@rajkishoreandia please refer the documentation for stable releases.The latest stable release in 2.0.9 , use it for Xcode 9.x , we are still working on Xcode 10 support.

**Comment by iThink32** [comment]
@rajkishoreandia we have released a new version of react-native-razorpay , have a look.But please don't forget to go through the readme.

**Comment by iThink32** [comment]
@rajkishoreandia the details of the latest stable version is in the readme of this repo anyway it is 2.0.13

**Comment by Balasnest** [comment]
Still facing this issue.
**react-native-razorpay**: 2.0.10 (Tired with 2.0.11, 2.0.13)
**react-native**: 0.56.0
```
error: bundling failed: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: .../node_modules/react-native-razorpay/node_modules/react-native/Libraries/Animated/release/package.json collides with .../node_modules/react-native/Libraries/Animated/release/package.json
```
