### ISSUE TITLE
Duplicate module name: react-animated

### ISSUE THREAD

**Issue by Balasnest** [razorpay/react-native-razorpay#124]
"react-native-razorpay": "2.0.8" (same issue happening in 2.0.9, 2.0.10, 2.0.11).[ Package.json of this lib.](http://prntscr.com/l1ieu9). Tried deleting and install package, node_modules. 

```
watchman watch-del-all
rm -rf node_modules && npm install
rm -fr $TMPDIR/react-*
npm cache clean
npm start -- --reset-cache
```

**Any idea why this happening?**

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /.../node_modules/react-native/Libraries/Animated/release/package.json collides with /.../node_modules/react-native-razorpay/node_modules/react-native/Libraries/Animated/release/package.json
```
![download](https://user-images.githubusercontent.com/6050520/46389422-46ac9900-c6ef-11e8-9add-2f9f114dcb16.png)

```

**React Native Environment Info:**
    
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 61.57 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    
     Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 4.6.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    
    SDKs:
      iOS SDK:
        Platforms: iOS 11.3, macOS 10.13, tvOS 11.3, watchOS 4.3
    
     IDEs:
      Android Studio: 3.0
      Xcode: 9.3.1
    
     npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    
     npmGlobalPackages:
      react-native-checkbox: 2.0.0
      react-native-cli: 2.0.1
      react-native-datepicker: 1.6.0
      react-native-git-upgrade: 0.2.7

**Comment by iThink32** [comment]
@Balasnest closing this as you mentioned that this issue has been fixed in another ticket.

**Comment by Balasnest** [comment]
@iThink32 I am still facing this problem. I have tired adding files into blacklist. But no change. Any idea how to resolve this problem? 

**react-native:0.56**
```
const blacklist = require('metro/src/blacklist')

module.exports = {
  getBlacklistRE() {
    return blacklist([
      /node_modules\/react-native-razorpay\/node_modules\/react-native\/.*/
    ])
  },
}
```

**Comment by perminder-klair** [comment]
ditto same error, please resolve guys

**Comment by iThink32** [comment]
@perminder-klair tagged you in a solution , please check.

**Comment by jkolyer** [comment]
> @perminder-klair tagged you in a solution , please check.

Can you provide link to solution for other people please?
