### ISSUE TITLE
'RazorpayCheckout' has different definitions in different modules; first difference is defined here found 1 referenced protocol

### ISSUE THREAD

**Issue by niyasmhdth** [razorpay/react-native-razorpay#292]
## Description
'RazorpayCheckout' has different definitions in different modules; first difference is defined here found 1 referenced protocol, shows an error after updating to xcode 12,

* **Specific to iOS Users:-**
 I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
2.2.0

## Xcode Version (iOS) :
xCode 12

## Razorpay-pod version (iOS) :
 - razorpay-pod (1.1.7)

### What you did:
After upgrading to xCode 12 facing this issue

### What happened:
When ios was running , facing this issue

**Comment by Nautiyalsachin** [comment]
Hey @niyasmhdth , can you try running the project in xcode first and share the error logs here

**Comment by niyasmhdth** [comment]
I think the issue is with xcode 12 , the update came out today, and my mac
has auto update, so it updated my xcode from 11 to 12, now I downloaded
xcode 11 and it works fine

**Comment by niyasmhdth** [comment]
*@interface* RazorpayCheckout : NSObject <RCTBridgeModule>

'RazorpayCheckout' has different definitions in different modules; first
difference is defined here found 1 referenced protocol

**Comment by niyasmhdth** [comment]
<img width="1402" alt="Screenshot 2020-09-17 at 7 41 37 PM" src="https://user-images.githubusercontent.com/44252714/93482943-e33cc580-f91d-11ea-8d36-eb3de063a75d.png">
Screenshot of Xcode 12
When I change the command-line tool from Xcode 12.0 to Xcode 11.7 in Preference > Location.
Switching command line works

**Comment by philly25** [comment]
Error is the same as here #286

**Comment by RomaJZ** [comment]
> <img alt="Screenshot 2020-09-17 at 7 41 37 PM" width="1402" src="https://user-images.githubusercontent.com/44252714/93482943-e33cc580-f91d-11ea-8d36-eb3de063a75d.png">
> 
> Screenshot of Xcode 12 When I change the command-line tool from Xcode 12.0 to Xcode 11.7 in Preference > Location. Switching command line works

Could you help me to understand how to make Xcode use multiple versions of Command Line Tools, please? I installed older version of CLT, but it doesn't show up anywhere.

**Comment by niyasmhdth** [comment]
@RomaJZ I didn't download just the CLT of 11.7, I went to the apple developer website and downloaded the Xcode 11.7 full file and added as separate xcode app in applications folder

**Comment by vivekexc** [comment]
Same issue. Any solution so far apart from downgrading to 11.7?
How to make it work with Xcode 12?

**Comment by niyasmhdth** [comment]
@vivekexc Even I’m looking for solution, for time being I’m using CLT 11.7 , waiting for razorpay to fix the issue. 😊

**Comment by Nautiyalsachin** [comment]
Hi @niyasmhdth, I am working on this issue, will post you an update as soon as I'll find the solution.

**Comment by niyasmhdth** [comment]
@Nautiyalsachin Thank you 😊

**Comment by dap221104** [comment]
@Nautiyalsachin Keep us updated. We are also facing same issue.

**Comment by ajitupapp** [comment]
@niyasmhdth Yes, I am facing the same issue as you after xcode 12 update.

**Comment by Nautiyalsachin** [comment]
Hi Everyone, As I can see there is something wrong with React-Native platform as there are so many issues coming up related to XCode 12. 

Here are some open issues on react Native like [30000](https://github.com/facebook/react-native/issues/30000), [29846](https://github.com/facebook/react-native/issues/29846), [29984](https://github.com/facebook/react-native/issues/29984), and many more.

I'll ask you guys to wait for the next React Native release or at least let them add some updates, as internally there are so many things breaking up.

They are also working on the new version release [v0.64.0 Discussion](https://github.com/react-native-community/releases/issues/207). Till then, I'll still be trying to fix this issue, and for any new updates, I'll keep you posted here.

**Comment by GovindSinghTak** [comment]
I am also facing the same issue with xcode 12

**Comment by LAKSHITgoel** [comment]
@Nautiyalsachin is there some way we can fix this by changing the native code?

**Comment by philly25** [comment]
@Nautiyalsachin Seems like this [thread](https://developer.apple.com/forums/thread/658012) is our case.

**Comment by philly25** [comment]
The only workaround for now to resolve conflict with Swift class name is to rename RN module name.

**Comment by weingenious72** [comment]
@philly25 gets an undefined error code after changing the native code.


![Simulator Screen Shot - iPhone 11 - 2020-10-10 at 12 35 52](https://user-images.githubusercontent.com/61498552/95648489-42dd5980-0af5-11eb-9f4e-debb68211bf1.png)

**Comment by philly25** [comment]
@weingenious72 It works for me. At least I can build app and payments works as usual. 
I think you should create another issue for your problem and provide some logs in it.

**Comment by kathirsuresh** [comment]
@philly25 its possible to explain more about ur changes

**Comment by philly25** [comment]
@kathirsuresh The issue raised because of the equal interface name `RazorpayCheckout`:

1. Razorpay SDK: interface in `<Razorpay/Razorpay-Swift.h>` (we import it in `RazorpayCheckout.m`)
2. React Native module: interface in `RazorpayCheckout.h`

Because we can't modify Razorpay SDK (swift code), all we can do is to rename React Native module interface to avoid conflict. That's what I've done.

**Comment by Nautiyalsachin** [comment]
> @Nautiyalsachin Seems like this thread is our case.

Yes, @philly25. This is happening internally as the framework is getting compiled again and maybe the shared library resources are getting certain conflicts. 

Agree with you here, if you change the class name from `RazorpayCheckout` to 'Razorpay' then it may start working. But still there is some major issue with React Native right now. As I am not even able to create a sample app using Xcode 12.

**Comment by imrahulpatel** [comment]
please change according to this link , the issue is fixed for me in xcode 12.1
https://github.com/razorpay/react-native-razorpay/pull/297/files/ea490ff7669c629010a74f41de6c4d61a74c1c05

**Comment by rohithramachandran** [comment]
Can we get this published in npm ? Seems like npm is still holding old version

**Comment by chakrihacker** [comment]
Please release a new version

**Comment by gauthampait** [comment]
Yes, please release the new version on npm ☹️ we've been waiting for so long now.

**Comment by Nautiyalsachin** [comment]
Hey @gauthampait, i am working on it, releasing it soon.

**Comment by akhilumapathe** [comment]
Any update/

**Comment by Nautiyalsachin** [comment]
Hi @akhilumapathe, we have released the new plugin v2.2.2 with the changes.

**Comment by eramudeep** [comment]
Still getting the same problem 
xcode : Version 12.2 (12B45b)
"react-native-razorpay": "^2.2.1",
react-native-cli: 2.0.1
node : v12.18.3

**Comment by Nautiyalsachin** [comment]
@eramudeep : Your react-native-razorpay package is still 2.2.1, It should be v2.2.2. 

Try removing and adding it again.

**Comment by wazzah-marham** [comment]
I am also facing this issue on Xcode 12.3? Is there any fix it yet ?

**Comment by Nautiyalsachin** [comment]
Have you tried updating our plugin to latest version v2.2.2? And also please update your pods by using `pod update` from your ios folder.

**Comment by anmolpandeyy** [comment]
> Have you tried updating our plugin to latest version v2.2.2? And also please update your pods by using `pod update` from your ios folder.

@Nautiyalsachin I'm getting the same error with v2.2.2 and even with the current latest v2.2.4. This is only happening in release scheme and not debug in iOS.
Xcode: 12.2
React-Native: 0.63.2
react-native-razorpay: 2.2.4
razorpay-pod (1.1.12)

**Comment by Nautiyalsachin** [comment]
Hey @anmolpandeyy, change **Build Active Architecture Only** to yes for both release and debug.

**Comment by nkpatnis** [comment]
changeing Build **Active Architecture Only** to yes for debug/staging or release also not working.

**Comment by nkpatnis** [comment]
changing **Build Active Architecture Only** to yes will work only when we change it in build configuration of the lib.

**Comment by Nautiyalsachin** [comment]
@nkpatnis I would suggest you to check your `.xcworkspace` > `build settings` by comparing it with our [sample app](https://github.com/razorpay/react-native-razorpay/tree/master/example/SampleProject). You might have modified something which is causing this issue. Let me know if that works for you.

**Comment by gauravgg** [comment]
> @nkpatnis I would suggest you to check your `.xcworkspace` > `build settings` by comparing it with our [sample app](https://github.com/razorpay/react-native-razorpay/tree/master/example/SampleProject). You might have modified something which is causing this issue. Let me know if that works for you.

Same happening with the Sample Project in XCode 12.5. Please help me with the solution
